---
title: "462final"
output: html_document
date: "2025-05-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




library(tidyverse)
library(ggpubr)
library(rstatix)

```{r}
data1 <- read.csv("new_retail_data.csv") 
data1 <- head(data1, 500)
head(data1)
```





```{r}
library(tidyverse)
library(ggpubr)



data1 <- subset(data1, 
                !is.na(Ratings) & Ratings != "" &
                !is.na(Product_Category) & Product_Category != "" &
                !is.na(Gender) & Gender != "" &
                !is.na(Total_Amount) & Total_Amount != "" &
                !is.na(Customer_Segment) & Customer_Segment != "" &
                !is.na(Total_Purchases) & Total_Purchases != "" &
                !is.na(Age) & Age != "" &
                !is.na(Year) & Year != "")



```



```{r}

#Age group related insights

data1 <- data1 %>%
  mutate(Age_Group = case_when(
    Age < 30 ~ "Young",
    Age >= 30 & Age < 50 ~ "Middle-aged",
    Age >= 50 ~ "Older"
  ))
data1 %>%
  group_by(Age_Group) %>%
  summarise(total_spending = sum(Total_Amount)) %>%
  ggplot(aes(x = Age_Group, y = total_spending, fill = Age_Group)) +
  geom_col() +
  labs(title = "Total Spending by Age Group", y = "Total Amount") +
  theme_minimal()


age_product <- data1 %>%
  group_by(Age_Group, Product_Category) %>%
  summarise(count = n(), .groups = 'drop')



ggplot(age_product, aes(x = Product_Category, y = count, fill = Age_Group)) +
  geom_col(position = "dodge") +
  labs(title = "Product Preferences by Age Group", x = "Product Category", y = "Number of Purchases") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}
# Brand related insights

brand_sales <- data1 %>%
  group_by(Product_Brand) %>%
  summarise(total_sales = sum(Total_Amount), .groups = "drop")

ggplot(brand_sales, aes(x = reorder(Product_Brand, -total_sales), y = total_sales)) +
  geom_col(fill = "steelblue") +
  labs(title = "Total Sales by Brand",
       x = "Product Brand",
       y = "Total Sales") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


brand_type_spending <- data1 %>%
  group_by(Product_Brand, Product_Type) %>%
  summarise(total_spending = sum(Total_Amount), .groups = "drop")

ggplot(brand_type_spending, aes(x = Product_Type, y = total_spending, fill = Product_Brand)) +
  geom_col(position = "dodge") +
  labs(title = "Total Spending by Product Brand and Type", x = "Product Type", y = "Total Spending") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


electronics_ratings <- data1 %>%
  filter(Product_Category == "Electronics") %>%
  group_by(Product_Brand) %>%
  summarise(avg_rating = mean(Ratings), .groups = "drop")

ggplot(electronics_ratings, aes(x = reorder(Product_Brand, avg_rating), y = avg_rating, fill = Product_Brand)) +
  geom_col() +
  labs(title = "Average Rating by Product Brand in Electronics",
       x = "Product Brand",
       y = "Average Rating") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```






```{r}
# Gender related insights 



gender_total <- data1 %>%
  group_by(Gender) %>%
  summarise(total_spend = sum(Total_Amount))

ggplot(gender_total, aes(x = Gender, y = total_spend, fill = Gender)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Spending by Gender", y = "Total Amount") +
  theme_minimal()

# Total Spending by Gender and Product Category:
gender_category_spend <- data1 %>%
  group_by(Gender, Product_Category) %>%
  summarise(total_amount = sum(Total_Amount), .groups = "drop")


ggplot(gender_category_spend, aes(x = Product_Category, y = total_amount, fill = Gender)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Total Spending by Gender and Product Category",
       x = "Product Category",
       y = "Total Amount") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


ggplot(data1, aes(x = Gender, y = Ratings, fill = Gender)) +
  geom_boxplot() +
  labs(title = "Ratings by Gender", x = "Gender", y = "Customer Rating") +
  theme_minimal()






```

```{r}
# income related insights

income_spending <- data1 %>%
  group_by(Income) %>%
  summarise(total_spending = sum(Total_Amount))

ggplot(income_spending, aes(x = Income, y = total_spending, fill = Income)) +
  geom_col() +
  labs(title = "Total Spending by Income Level", y = "Total Amount") +
  theme_minimal()


income_product <- data1 %>%
  group_by(Income, Product_Category) %>%
  summarise(purchase_count = n(), .groups = "drop")

ggplot(income_product, aes(x = Product_Category, y = purchase_count, fill = Income)) +
  geom_col(position = "dodge") +
  labs(title = "Product Preferences by Income Level", y = "Number of Purchases") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


income_segment <- data1 %>%
  group_by(Income, Customer_Segment) %>%
  summarise(count = n(), .groups = "drop")

ggplot(income_segment, aes(x = Income, y = count, fill = Customer_Segment)) +
  geom_col(position = "dodge") +
  labs(title = "Customer Segment by Income Level", y = "Number of Customers") +
  theme_minimal()

```





